// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://botexzthlcmeuvsjbblh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJvdGV4enRobGNtZXV2c2piYmxoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4MzAwOTEsImV4cCI6MjA3MzQwNjA5MX0.uMB5zGfrqQLf77nvWl5XHGYxAzjbd-2b4iYhBSOfiIY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});